//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataProvider.Models.TradingData
{
	/// <summary>
	/// Database       : TradingData
	/// Data Source    : EMANUELEWIN
	/// Server Version : 5.6.15-log
	/// </summary>
	public partial class TradingDataDB : LinqToDB.Data.DataConnection
	{
		public TradingDataDB()
		{
		}

		public TradingDataDB(string configuration)
			: base(configuration)
		{
		}
	}
}
 
   